sonar.projectKey=telicent-oss_telicent-query_9f7ad616-b295-4f4a-88ec-7750a017343c
sonar.projectName=query-ui

sonar.sources=src
sonar.tests=src

# sources and tests both point at src/, so partition them explicitly
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/__tests__/**
sonar.exclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/__tests__/**,**/*.d.ts,src/setupTests.js,src/main.css

# written by `jest --coverage` into coverage/ via jest.config.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
