name: Test Helm chart
run-name: Unit Tests for Helm Chart

on:
  pull_request:
    branches:
      - main 

jobs:
  helm-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Run Helm unit tests
        uses: telicent-oss/shared-workflows/.github/actions/unit-helm-charts@feat/helm-unit-test
        with:
          chart: charts/query-ui